### ISSUE TITLE
Handling of proposal-in-review and disposition-* labels

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/mscbot-python#10]
- [x] When entering FCP, the bot needs to remove the `proposal-in-review` label.
- [x] When exiting FCP, the bot needs to remove the `disposition-*` label and add the `proposal-in-review` label.

**Comment by turt2live** [comment]
more specifically, when the FCP is proposed it needs to drop the `proposal-in-review` label. If the FCP gets cancelled for whatever reason, it needs to add it back.

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/mscbot-python/commit/1d786dfdbac270ad404828afd2f382a77ff7c954
