### ISSUE TITLE
Include when an FCP will complete in the comment denoting FCP

### ISSUE THREAD

**Issue by clokep** [matrix-org/mscbot-python#18]
**Describe the bug**
When an MSC goes into the FCP a comment is added to the PR like: "🔔 This is now entering its final comment period, as per the review above. 🔔"

It would be really awesome if this included *when* (assuming nothing goes wrong) the FCP would complete. I always forget whether the final comment period is 5 days, 7 days, or something else.

**Comment by turt2live** [comment]
It's currently 5 days, btw.
